### ISSUE TITLE
9.empty 伪类的妙用

### ISSUE THREAD

**Issue by CruxF** [CruxF/StudyCss#9]
:empty 伪类是用来匹配空标签元素，一般情况下有如下应用场景
- 1、隐藏空元素：例如，某个模块里的内容是动态的，可能是列表，也可能是按钮，这些模块容器常包含影响布局的CSS属性，如margin、padding属性等。当然，这些模块里面有内容的时候，布局显示效果是非常好的，然儿一旦这些模块里面的内容为空，页面上就会有一块很大的明显的空白，效果就不好，这种情况下使用 :empty 伪类控制一下就再好不过了。无需额外的JavaScript逻辑判断，直接使用CSS就可以实现动态样式效果，唯一需要注意的，当列表内容缺失的时候，一定要把空格也去掉，否则:empty 伪类不会匹配。
- 2、字段缺失智能提示：用户某些信息字段是缺失的，此时由于开发人员应该使用其他占位字符示意这里没有内容，如短横线（-）或者直接使用文字提示。但是多年的开发经验告诉我，开发人员非常容易忘记这里的特殊处理，最终导致布局混乱，信息难懂。但如今，我们就不用担心这样的合作问题了，直接使用CSS就可以处理这种情况。
- 3、数据为空提示：实际开发中类似的场景还有很多。例如，表格中的备注信息经常都是空的，此时可以这样处理
```css
td:empty::before{
  content: '- -';
  color: gray;
}
```

除此之外，还有一类典型场景需要用到 :empty 伪类，那就是动态Ajax加载数据为空的情况。当一个新用户进入一个产品的时候，很多模块内容是没有的。要是在过去，我们需要在Javascript代码中做 if 判断，如果没有值，我们要吐出”没有结果“或者”没有数据“的信息。但是现在，有了 :empty 伪类，直接把这个工作交给CSS就可以了。
```css
.cs-search-module:empty::before {
  content: '没有搜索结果'；
  display: block;
  line-height: 300px;
  text-align: center;
  color: gray;
}
```

总之，这种方法非常好用，可以节约大量的开发时间，同时体验更好，维护更方便，因为可以使用同一个类名使整站提示信息保持一致：
```css
.cs-article-module:empty::before{
  content: '暂无数据；
  display: block;
  line-height: 300px;
  text-align: center;
  color: gray;
}
```

相关demo代码：
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>:empty 伪类的妙用</title>
    <style>
      /* 1.对空标签元素做特殊处理 */
      .cs-empty:empty {
        width: 120px;
        height: 200px;
        padding: 20px;
        border: 10px dashed #ccc;
      }
      /* 2.隐藏空标签元素 */
      .bs-empty:empty {
        display: none;
      }
      /* 3.字段缺失智能提示 */
      dt {
        float: left;
      }
      dd:empty::before {
        content: "暂无";
        color: gray;
      }
    </style>
  </head>
  <body>
    <div class="cs-empty"></div>
    <div class="cs-empty">这是有内容的1</div>

    <div class="bs-empty"></div>
    <div class="bs-empty">这是有内容的2</div>

    <dl>
      <dt>姓名：</dt>
      <dd>张三</dd>
      <dt>性别：</dt>
      <dd></dd>
      <dt>手机：</dt>
      <dd></dd>
      <dt>邮箱：</dt>
      <dd></dd>
    </dl>
  </body>
</html>
```
